### ISSUE TITLE
Calling run() trashes AST passed in to constructor

### ISSUE THREAD

**Issue by mercmobily** [NeilFraser/JS-Interpreter#171] opened 2020-01-14 04:14 UTC
I apologise if this question has a very obvious answer.

Consider the following code:

````
var args = [1]
const code = 'function testing(a) { return a };testing(args[0])'
const myInterpreter = new JSInterpreter.Interpreter(code)
myInterpreter.setValueToScope('args', myInterpreter.nativeToPseudo(args))
myInterpreter.run()
console.log(myInterpreter.pseudoToNative(myInterpreter.value))

var args = [2]
myInterpreter.setValueToScope('args', myInterpreter.nativeToPseudo(args))
myInterpreter.run()
````

The output is '1' both times.
Why isn't "args" in the compiler overwritten? Is there a call I can use to "reset" the interpreter, but without losing the code compilation?

**Comment by NeilFraser** [comment] 2020-01-14 06:41
There's a misunderstanding here:

> const code = 'function testing(a) { return a };testing(args[0])'
> const myInterpreter = new JSInterpreter.Interpreter(code)

This creates the interpreter, ready to go.

> myInterpreter.run()

This executes the code until there is no more code to run.

> myInterpreter.run()

This returns immediately having run nothing, since all the code has already executed.  It does not reset and start running the code again.

There are two approaches to what you are looking for.  One is to just throw away your 'used' interpreter and create a new one:

```
const code = 'function testing(a) { return a };testing(args[0])';
let myInterpreter = new JSInterpreter.Interpreter(code);
myInterpreter.run();

myInterpreter = new JSInterpreter.Interpreter(code);
myInterpreter.run();
```

Creating a new interpreter is fast and efficient, so there's no problem with this approach.  The only issue is if you want to save some state between these two executions.  If there are variables you want to preserve, then you need to take a different approach:

```
const code = 'function testing(a) { return a };testing(args[0])';
const myInterpreter = new JSInterpreter.Interpreter(code);
myInterpreter.run();

myInterpreter.appendCode('testing(args[0]);');
myInterpreter.run();
```

The first `run()` will define the function and call it once.  The second `run()` will call it a second time.

I hope this answers your question, feel free to reopen this issue if not.

**Comment by mercmobily** [comment] 2020-01-14 08:56
Thank you so much for supporting us using the software Neil. I really,
really appreciate it.
My rational was that I thought I should avoid running new
JSInterpreter.Interpreter(code) as it was expensive -- the whole code needs
to be re-parsed etc.
So, the idea was that I would get js-interpreter to do all of the parsing
etc. once, and then run the code more than once (no, no state needs to be
preserved. In fact, quite the contrary).
But... am I wrong? You write that creating a new interpreter is fast and
efficient. But does that mean that it will need to reparse the whole lot
every time?
Thank you again.

**Comment by NeilFraser** [comment] 2020-01-14 09:54
If you notice parsing the code is slow, you can parse it yourself, cache the result, and just feed the AST to the JS-Interpreter:

```
const code = 'function testing(a) { return a };testing(args[0])';
const ast = acorn.parse(code, Interpreter.PARSE_OPTIONS);
let myInterpreter = new JSInterpreter.Interpreter(ast);
myInterpreter.run();

myInterpreter = new JSInterpreter.Interpreter(ast);
myInterpreter.run();
```

`acorn` is part of the JS-Interpreter package and does the code to AST generation.  The `Interpreter` constructor can take either a raw code string, or the AST.

**Comment by mercmobily** [comment] 2020-01-14 22:12
I must be doing something very stupid...

This doesn't work -- the second time, it returns 'undefined'

````
let args, myInterpreter
const code = 'function testing(a) { return a };testing(args[0])'
const ast = global.acorn.parse(code)

args = [1]
myInterpreter = new JSInterpreter.Interpreter(ast)
myInterpreter.setValueToScope('args', myInterpreter.nativeToPseudo(args))
myInterpreter.run()
console.log('ONE', myInterpreter.pseudoToNative(myInterpreter.value))

args = [2]
myInterpreter = new JSInterpreter.Interpreter(ast)
myInterpreter.setValueToScope('args', myInterpreter.nativeToPseudo(args))
myInterpreter.run()

console.log('TWO', myInterpreter.pseudoToNative(myInterpreter.value))
````

However, passing `code` instead of `ast` to new JSInterpreter.Interpreter()
will work. I just can't explain why!

**Comment by mercmobily** [comment] 2020-01-14 22:28
Update: if I use https://github.com/pvorb/clone on the AST and use
JSInterpreter with a copy of the AST, the code works.
So... something is happening to the AST once it's run.
Is there any way to "rewind" it, so that I don't have to clone it?

**Comment by mercmobily** [comment] 2020-01-14 22:45
Sorry for spamming... I just noticed that the AST's body is _totally_
zapped after calling run()!
No wonder clone() works :D
I tried to save a copy of AST's body but it looks like Acorn zaps it "from
the inside" so to speak.
So... is cloning "it"?

**Comment by cpcallen** [comment] 2020-01-14 22:54
> I just noticed that the AST's body is _totally_ zapped after calling run()!

That is definitely a bug.

**Comment by NeilFraser** [comment] 2020-01-15 08:57
Trashing the AST is not a bug, it's a feature.  See #124.

:-)

**Comment by mercmobily** [comment] 2020-01-15 09:12
But this makes it impossible to enact a possibly common use case where you
might want to run th same code over and over again without recompiling...

Could this be an option?

**Comment by NeilFraser** [comment] 2020-01-15 09:22
I think this thread is based on the false premise that parsing an AST is expensive.  By my timings (Chrome on a Mid 2014 Macbook) acorn.parse() of a 263 KB code blob (interpreter.js) takes 25ms.  That's really crazy fast.

**Comment by mercmobily** [comment] 2020-01-15 11:34
Have a function and run it 100 times per second... And it becomes a problem
Neil!

**Comment by cpcallen** [comment] 2020-01-15 20:25
As discussed with @NeilFraser offline: there is an easy fix, which is to copy the `Program` node and its `.body` array when constructing the `Interpreter` instance.

This also protects the original AST from being modified by `appendCode`, as it is at present.

A fix should be forthcoming shortly.

**Comment by mercmobily** [comment] 2020-01-16 01:22
Hi,

Let me know once the fix is up, so that I can stop clone() ing!

Merc.

**Comment by NeilFraser** [comment] 2020-01-16 20:40
Should be fixed now.

**Closed by NeilFraser** 2020-01-16 20:40 UTC
